/**
 * THE ARCHIVIST - CATEGORY MAP
 * * This file contains the seed data for the Serendipity Engine.
 * It maps specific Wikipedia categories to broader intellectual domains.
 * * To expand the tool, add new entries here following the format:
 * { id: "Category:Name_on_Wikipedia", domain: "Your_Defined_Domain", label: "Display Label" }
 */

window.CATEGORY_MAP = [
    // Philosophy
    { id: "Category:Philosophical_concepts", domain: "Philosophy", label: "General Philosophy" },
    { id: "Category:Epistemology", domain: "Philosophy", label: "Epistemology" },
    { id: "Category:Ethics", domain: "Philosophy", label: "Ethics" },
    { id: "Category:Paradoxes", domain: "Philosophy", label: "Paradoxes" },
    { id: "Category:Metaphysics", domain: "Philosophy", label: "Metaphysics" },
    { id: "Category:Existentialism", domain: "Philosophy", label: "Existentialism" },
    { id: "Category:Political_philosophy", domain: "Philosophy", label: "Political Phil." },
    { id: "Category:Phenomenology", domain: "Philosophy", label: "Phenomenology" },
    { id: "Category:Logic", domain: "Philosophy", label: "Formal Logic" },
    { id: "Category:Philosophy_of_mind", domain: "Philosophy", label: "Phil. of Mind" },
    { id: "Category:Post-structuralism", domain: "Philosophy", label: "Post-structuralism" },
    { id: "Category:Eastern_philosophy", domain: "Philosophy", label: "Eastern Phil." },
    { id: "Category:Aesthetics", domain: "Philosophy", label: "Aesthetics" },
    { id: "Category:Stoicism", domain: "Philosophy", label: "Stoicism" },
    { id: "Category:Utilitarianism", domain: "Philosophy", label: "Utilitarianism" },
    { id: "Category:Philosophy_of_science", domain: "Philosophy", label: "Phil. of Science" },
    { id: "Category:Bioethics", domain: "Philosophy", label: "Bioethics" },
    { id: "Category:Environmental_ethics", domain: "Philosophy", label: "Env. Ethics" },
    { id: "Category:Theology", domain: "Philosophy", label: "Theology" },
    { id: "Category:Enlightenment_philosophy", domain: "Philosophy", label: "The Enlightenment" },
    { id: "Category:Analytic_philosophy", domain: "Philosophy", label: "Analytic Phil." },
    { id: "Category:Continental_philosophy", domain: "Philosophy", label: "Continental Phil." },

    // Social Sciences
    { id: "Category:Cultural_anthropology", domain: "Social Science", label: "Cultural Anthro" },
    { id: "Category:Social_psychology", domain: "Social Science", label: "Social Psych" },
    { id: "Category:Developmental_psychology", domain: "Social Science", label: "Dev. Psych" },
    { id: "Category:Human_geography", domain: "Social Science", label: "Human Geography" },
    { id: "Category:Demography", domain: "Social Science", label: "Demography" },
    { id: "Category:Criminology", domain: "Social Science", label: "Criminology" },
    { id: "Category:Media_studies", domain: "Social Science", label: "Media Studies" },
    { id: "Category:Social_stratification", domain: "Social Science", label: "Social Stratification" },
    { id: "Category:Cognitive_biases", domain: "Social Science", label: "Cognitive Biases" },
    { id: "Category:Archetypes", domain: "Social Science", label: "Archetypes" },
    { id: "Category:Cyberculture", domain: "Social Science", label: "Cyberculture" },
    { id: "Category:Urban_sociology", domain: "Social Science", label: "Urban Sociology" },
    { id: "Category:Anthropology_of_religion", domain: "Social Science", label: "Anthro of Religion" },
    { id: "Category:Environmental_social_science", domain: "Social Science", label: "Env. Social Science" },
    { id: "Category:Science_and_technology_studies", domain: "Social Science", label: "STS" },
    { id: "Category:Linguistics", domain: "Social Science", label: "Linguistics" },
    { id: "Category:Sociolinguistics", domain: "Social Science", label: "Sociolinguistics" },
    { id: "Category:Social_movements", domain: "Social Science", label: "Social Movements" },
    { id: "Category:Globalization", domain: "Social Science", label: "Globalization" },

    // Science
    { id: "Category:Scientific_theories", domain: "Science", label: "Scientific Theories" },
    { id: "Category:Physical_cosmology", domain: "Science", label: "Cosmology" },
    { id: "Category:Cognitive_science", domain: "Science", label: "Cognitive Science" },
    { id: "Category:Fluid_dynamics", domain: "Science", label: "Fluid Dynamics" },
    { id: "Category:Oceanography", domain: "Science", label: "Oceanography" },
    { id: "Category:Materials_science", domain: "Science", label: "Material Science" },
    { id: "Category:Quantum_mechanics", domain: "Science", label: "Quantum Mechanics" },
    { id: "Category:Complexity_theory", domain: "Science", label: "Complexity Theory" },
    { id: "Category:Cybernetics", domain: "Science", label: "Cybernetics" },
    { id: "Category:String_theory", domain: "Science", label: "String Theory" },
    { id: "Category:Evolutionary_biology", domain: "Science", label: "Evolutionary Bio" },
    { id: "Category:Chaos_theory", domain: "Science", label: "Chaos Theory" },
    { id: "Category:Neuroscience", domain: "Science", label: "Neuroscience" },
    { id: "Category:Behavioral_genetics", domain: "Science", label: "Behavioral Genetics" },
    { id: "Category:Climatology", domain: "Science", label: "Climatology" },
    { id: "Category:Immunology", domain: "Science", label: "Immunology" },
    { id: "Category:Astrophysics", domain: "Science", label: "Astrophysics" },
    { id: "Category:Glaciology", domain: "Science", label: "Glaciology" },
    { id: "Category:Public_health", domain: "Science", label: "Public Health" },
    { id: "Category:History_of_medicine", domain: "Science", label: "Hist. of Medicine" },
    { id: "Category:Artificial_intelligence", domain: "Science", label: "AI Theory" },
    { id: "Category:Cryptography", domain: "Science", label: "Cryptography" },
    { id: "Category:Nanotechnology", domain: "Science", label: "Nanotechnology" },
    { id: "Category:Forensic_science", domain: "Science", label: "Forensic Science" },
    { id: "Category:Quantum_computing", domain: "Science", label: "Quantum Computing" },
    { id: "Category:Renewable_energy", domain: "Science", label: "Renewable Energy" },
    { id: "Category:Spaceflight", domain: "Science", label: "Spaceflight" },
    { id: "Category:Mycology", domain: "Science", label: "Mycology" },
    { id: "Category:Ornithology", domain: "Science", label: "Ornithology" },
    { id: "Category:Entomology", domain: "Science", label: "Entomology" },
    { id: "Category:Botany", domain: "Science", label: "Botany" },
    { id: "Category:Astrobiology", domain: "Science", label: "Astrobiology" },
    { id: "Category:Network_science", domain: "Science", label: "Network Science" },
    { id: "Category:Data_science", domain: "Science", label: "Data Science" },
    { id: "Category:Thermodynamics", domain: "Science", label: "Thermodynamics" },
    { id: "Category:Particle_physics", domain: "Science", label: "Particle Physics" },
    { id: "Category:Optics", domain: "Science", label: "Optics" },

    // Arts & Culture
    { id: "Category:Art_movements", domain: "Arts", label: "Art Movements" },
    { id: "Category:Architectural_styles", domain: "Arts", label: "Architecture" },
    { id: "Category:Music_theory", domain: "Arts", label: "Music Theory" },
    { id: "Category:Urban_planning", domain: "Arts", label: "Urban Planning" },
    { id: "Category:Game_studies", domain: "Arts", label: "Game Studies" },
    { id: "Category:Film_noir", domain: "Arts", label: "Film Noir" },
    { id: "Category:Typography", domain: "Arts", label: "Typography" },
    { id: "Category:Bauhaus", domain: "Arts", label: "The Bauhaus" },
    { id: "Category:Brutalist_architecture", domain: "Arts", label: "Brutalism" },
    { id: "Category:Film_theory", domain: "Arts", label: "Film Theory" },
    { id: "Category:Classical_music_eras", domain: "Arts", label: "Classical Music" },
    { id: "Category:Art_Deco", domain: "Arts", label: "Art Deco" },
    { id: "Category:Comparative_literature", domain: "Arts", label: "Comp. Literature" },
    { id: "Category:Art_history_methods", domain: "Arts", label: "Art History Methods" },
    { id: "Category:Surrealism", domain: "Arts", label: "Surrealism" },
    { id: "Category:Renaissance_art", domain: "Arts", label: "Renaissance Art" },
    { id: "Category:Literary_theory", domain: "Arts", label: "Literary Theory" },
    { id: "Category:Postmodern_literature", domain: "Arts", label: "Postmodern Lit." },
    { id: "Category:Abstract_expressionism", domain: "Arts", label: "Abstract Exp." },
    { id: "Category:Neoclassicism", domain: "Arts", label: "Neoclassicism" },
    { id: "Category:Victorian_literature", domain: "Arts", label: "Victorian Lit." },
    { id: "Category:Romanticism", domain: "Arts", label: "Romanticism" },
    { id: "Category:Magical_realism", domain: "Arts", label: "Magical Realism" },
    { id: "Category:Cyberpunk", domain: "Arts", label: "Cyberpunk" },
    { id: "Category:Gothic_fiction", domain: "Arts", label: "Gothic Fiction" },
    { id: "Category:Calligraphy", domain: "Arts", label: "Calligraphy" },
    { id: "Category:Pottery", domain: "Arts", label: "Pottery" },
    { id: "Category:Textile_arts", domain: "Arts", label: "Textile Arts" },
    { id: "Category:Printmaking", domain: "Arts", label: "Printmaking" },
    { id: "Category:Modernist_literature", domain: "Arts", label: "Modernism" },
    { id: "Category:Beat_Generation", domain: "Arts", label: "Beat Generation" },
    { id: "Category:Renaissance_literature", domain: "Arts", label: "Renaissance Lit." },

    // History & Politics
    { id: "Category:Ancient_civilizations", domain: "History", label: "Ancient History" },
    { id: "Category:Sociological_theories", domain: "History", label: "Sociology" },
    { id: "Category:Linguistics", domain: "History", label: "Linguistics" },
    { id: "Category:Archaeology", domain: "History", label: "Archaeology" },
    { id: "Category:Classical_mythology", domain: "History", label: "Mythology" },
    { id: "Category:Political_geography", domain: "History", label: "Geopolitics" },
    { id: "Category:Historiography", domain: "History", label: "Historiography" },
    { id: "Category:World_mythology", domain: "History", label: "World Mythology" },
    { id: "Category:Military_history", domain: "History", label: "Military History" },
    { id: "Category:Diplomatic_history", domain: "History", label: "Diplomatic History" },
    { id: "Category:Intellectual_history", domain: "History", label: "Intellectual History" },
    { id: "Category:History_of_science", domain: "History", label: "History of Science" },
    { id: "Category:Comparative_religion", domain: "History", label: "Comp. Religion" },
    { id: "Category:Cartography", domain: "History", label: "Cartography" },
    { id: "Category:Numismatics", domain: "History", label: "Numismatics" },
    { id: "Category:Vexillology", domain: "History", label: "Vexillology" },
    { id: "Category:Feudal_Japan", domain: "History", label: "Feudal Japan" },
    { id: "Category:Mesoamerican_civilizations", domain: "History", label: "Mesoamerica" },
    { id: "Category:Cold_War", domain: "History", label: "Cold War" },
    { id: "Category:Oral_history", domain: "History", label: "Oral History" },
    { id: "Category:Genealogy", domain: "History", label: "Genealogy" },
    { id: "Category:Psychohistory", domain: "History", label: "Psychohistory" },
    { id: "Category:Microhistory", domain: "History", label: "Microhistory" },
    { id: "Category:Industrial_Revolution", domain: "History", label: "Industrial Rev." },
    { id: "Category:Age_of_Discovery", domain: "History", label: "Age of Discovery" },
    { id: "Category:Silk_Road", domain: "History", label: "The Silk Road" },
    
    // Politics
    { id: "Category:Political_ideologies", domain: "Politics", label: "Political Ideologies" },
    { id: "Category:International_relations_theory", domain: "Politics", label: "IR Theory" },
    { id: "Category:Forms_of_government", domain: "Politics", label: "Forms of Gov." },
    { id: "Category:Public_policy", domain: "Politics", label: "Public Policy" },
    { id: "Category:Voting_systems", domain: "Politics", label: "Voting Systems" },
    { id: "Category:Postcolonialism", domain: "Politics", label: "Post-Colonialism" },
    { id: "Category:Human_rights", domain: "Politics", label: "Human Rights" },
    { id: "Category:Comparative_politics", domain: "Politics", label: "Comparative Politics" },
    { id: "Category:Political_campaigning", domain: "Politics", label: "Political Campaigning" },
    { id: "Category:Geopolitics", domain: "Politics", label: "Geopolitics" },
    { id: "Category:Psephology", domain: "Politics", label: "Psephology" },
    { id: "Category:Public_opinion", domain: "Politics", label: "Public Opinion" },
    { id: "Category:Civil_disobedience", domain: "Politics", label: "Civil Disobedience" },

    // Law
    { id: "Category:International_law", domain: "Law", label: "International Law" },
    { id: "Category:Legal_doctrines_and_principles", domain: "Law", label: "Legal Principles" },
    { id: "Category:Jurisprudence", domain: "Law", label: "Jurisprudence" },
    { id: "Category:Constitutional_law", domain: "Law", label: "Constitutional Law" },
    { id: "Category:Criminal_law", domain: "Law", label: "Criminal Law" },
    { id: "Category:Tort_law", domain: "Law", label: "Tort Law" },
    { id: "Category:Contract_law", domain: "Law", label: "Contract Law" },
    { id: "Category:Intellectual_property_law", domain: "Law", label: "IP Law" },
    { id: "Category:Admiralty_law", domain: "Law", label: "Maritime Law" },
    { id: "Category:Comparative_law", domain: "Law", label: "Comparative Law" },

    // Economics
    { id: "Category:Macroeconomics", domain: "Economics", label: "Macroeconomics" },
    { id: "Category:Behavioral_economics", domain: "Economics", label: "Behavioral Econ" },
    { id: "Category:Game_theory", domain: "Economics", label: "Game Theory" },
    { id: "Category:Political_economy", domain: "Economics", label: "Political Economy" },
    { id: "Category:International_political_economy", domain: "Economics", label: "Int. Pol. Economy" },
    { id: "Category:Urban_economics", domain: "Economics", label: "Urban Economics" },
    { id: "Category:Development_economics", domain: "Economics", label: "Development Econ" },
    { id: "Category:Labor_economics", domain: "Economics", label: "Labor Economics" },
    { id: "Category:Econometrics", domain: "Economics", label: "Econometrics" },
    { id: "Category:History_of_economic_thought", domain: "Economics", label: "History of Econ" },
    { id: "Category:Welfare_economics", domain: "Economics", label: "Welfare Econ" },
    { id: "Category:Industrial_organization", domain: "Economics", label: "Industrial Org" },
    { id: "Category:Environmental_economics", domain: "Economics", label: "Env. Economics" },
    { id: "Category:Economic_history", domain: "Economics", label: "Economic History" },
    { id: "Category:Economic_geography", domain: "Economics", label: "Economic Geography" },

    // Finance
    { id: "Category:Financial_markets", domain: "Finance", label: "Financial Markets" },
    { id: "Category:Economic_bubbles", domain: "Finance", label: "Economic Bubbles" },
    { id: "Category:Monetary_economics", domain: "Finance", label: "Monetary Theory" },
    { id: "Category:Investment", domain: "Finance", label: "Investment Theory" },
    { id: "Category:Corporate_finance", domain: "Finance", label: "Corp. Finance" },
    { id: "Category:Public_finance", domain: "Finance", label: "Public Finance" },
    { id: "Category:Financial_risk", domain: "Finance", label: "Risk Management" },
    { id: "Category:Derivatives_(finance)", domain: "Finance", label: "Derivatives" },
    { id: "Category:Actuarial_science", domain: "Finance", label: "Actuarial Science" },
    { id: "Category:Banking", domain: "Finance", label: "Banking" },
    { id: "Category:Financial_regulation", domain: "Finance", label: "Financial Regulation" },
    { id: "Category:Behavioral_finance", domain: "Finance", label: "Behavioral Finance" },

    // Mathematics
    { id: "Category:Number_theory", domain: "Mathematics", label: "Number Theory" },
    { id: "Category:Topology", domain: "Mathematics", label: "Topology" },
    { id: "Category:Combinatorics", domain: "Mathematics", label: "Combinatorics" },
    { id: "Category:Set_theory", domain: "Mathematics", label: "Set Theory" },
    { id: "Category:Graph_theory", domain: "Mathematics", label: "Graph Theory" },
    { id: "Category:Linear_algebra", domain: "Mathematics", label: "Linear Algebra" },
    { id: "Category:Probability_theory", domain: "Mathematics", label: "Probability" },
    { id: "Category:Mathematical_logic", domain: "Mathematics", label: "Math Logic" }
];